190226schema_version: "1.4"
recipe_id: "QUEIJO_NETE"
name: "Queijo Nete"
family: "fresco"
authorial: true

description: >
  Queijo autoral com processo sensível a proporções, tempo,
  observações manuais (floculação, ponto de corte),
  controle de pH e maturação controlada em câmara.

llm_policy:
  allowed_actions:
    - explain_step
    - clarify_doubts
    - rephrase_instruction
    - warn_risk
    - remind_action
  forbidden_actions:
    - calculate_proportions
    - advance_stage
    - skip_stage
    - override_measurements
    - change_timers

units:
  volume: "L"
  liquid: "ml"
  temperature: "C"
  time: "min"
  ph: "pH"

batch:
  milk_volume_l:
    required: true
    min: 10
    max: 200

inputs:
  - id: "MILK"
    name: "Leite"
    unit: "L"
    required: true

  - id: "FERMENT_LR"
    name: "Fermento LR"
    unit: "ml"
    dosing:
      mode: "per_2_liters"
      value: 1
    required: true
    storage: "freezer"

  - id: "FERMENT_DX"
    name: "Fermento DX"
    unit: "ml"
    dosing:
      mode: "per_2_liters"
      value: 1
    required: true
    storage: "freezer"

  - id: "FERMENT_KL"
    name: "Fermento KL"
    unit: "ml"
    dosing:
      mode: "per_20_liters"
      value: 8
    required: true
    storage: "freezer"

  - id: "RENNET"
    name: "Coalho"
    unit: "ml"
    dosing:
      mode: "per_20_liters"
      value: 1
    required: true

process:
  target_temperature_c: 32
  temperature_tolerance_c: 1
  target_final_ph: 5.2
  maturation_target_days: 90

stages:

  - id: 1
    name: "Separar o leite e medir parâmetros iniciais"
    type: "input"
    operator_input_required:
      - milk_volume_l
      - milk_temperature_c
      - milk_ph
    stored_values:
      - milk_volume_l
      - milk_temperature_c
      - milk_ph
    llm_guidance: >
      Confirme volume, temperatura e pH iniciais.
      Esses dados são importantes para rastreabilidade do lote.

  - id: 2
    name: "Calcular fermentos e coalho"
    type: "system"
    system_actions:
      - calculate_proportions
      - remind_remove_from_freezer

  - id: 3
    name: "Aquecer o leite"
    type: "heat"
    parameters:
      target_temp_c: 32
    validations:
      - rule: "temperature_between(31,33)"

  - id: 4
    name: "Adicionar fermentos LR e DX"
    type: "add"
    instructions:
      - "Adicionar fermento LR"
      - "Adicionar fermento DX"
      - "Mexer bem"
    timer:
      duration_min: 30
      blocking: true

  - id: 5
    name: "Adicionar fermento KL e coalho"
    type: "add"
    instructions:
      - "Adicionar fermento KL"
      - "Adicionar coalho"
      - "Mexer bem"
      - "Colocar a Lira"
    llm_guidance: >
      Explique a importância de aguardar floculação antes do corte.

  - id: 6
    name: "Anotar horário de floculação"
    type: "observe"
    operator_input_required:
      - flocculation_time
    stored_values:
      - flocculation_time
    expected_intent: "LogTimeIntent"
    expected_time_type: "floculação"
    input_prompt: "Registre o horário da floculação dizendo: 'hora da floculação às quinze e vinte'."

  - id: 7
    name: "Anotar horário do ponto de corte"
    type: "observe"
    operator_input_required:
      - cut_point_time
    stored_values:
      - cut_point_time
    expected_intent: "LogTimeIntent"
    expected_time_type: "corte"
    input_prompt: "Registre o horário do ponto de corte dizendo: 'hora do corte às quinze e vinte'."

  - id: 8
    name: "Corte da massa com a Lira"
    type: "cut"

  - id: 9
    name: "Corte complementar com espátula"
    type: "cut"

  - id: 10
    name: "Mexedura progressiva da massa"
    type: "stir"
    parameters:
      style: "progressive"
    timer:
      duration_min: 30
      blocking: true

  - id: 11
    name: "Enformagem com peneira e paninho"
    type: "mold"

  - id: 12
    name: "Dessoragem em mesa"
    type: "drain"
    parameters:
      duration_note: "alguns minutos"

  - id: 13
    name: "Medir pH inicial e registrar quantidade de peças"
    type: "measure"
    operator_input_required:
      - ph_value
      - pieces_quantity
    stored_values:
      - initial_ph
      - pieces_quantity
    expected_intent: "RegisterPHAndPiecesIntent"
    input_prompt: "Informe o pH inicial e a quantidade de peças dizendo: 'pH cinco vírgula quatro e seis peças'."

  - id: 14
    name: "Colocar na prensa"
    type: "press"
    operator_input_required:
      - press_start_time
    stored_values:
      - press_start_time
    expected_intent: "LogTimeIntent"
    expected_time_type: "prensa"
    input_prompt: "Registre o horário de início da prensagem dizendo: 'hora da prensa às quinze e vinte'."

  - id: 15
    name: "Virar queijos e medir pH (loop controlado)"
    type: "loop"
    loop_condition:
      until: "ph_value <= 5.2"
    max_loop_duration_hours: 1.5
    loop_actions:
      - "virar_queijos"
      - "medir_ph"
      - "registrar_ph"
    operator_input_required:
      - ph_value
    stored_values:
      - ph_measurements[]
      - turning_cycles_count
    expected_intent: "RegisterPHAndPiecesIntent"
    input_prompt: "Informe o pH atual dos queijos dizendo: 'pH cinco vírgula dois'."
    llm_guidance: >
      Se o pH atingir 5,2 antes de completar 1 hora e 30 minutos,
      o loop pode ser encerrado imediatamente.
      Cada loop representa uma virada dos queijos.

  - id: 16
    name: "Transferir para câmara de secagem"
    type: "transfer"
    timing:
      when: "apos_prensagem"

  - id: 17
    name: "Salga em tanque"
    type: "brine"
    timer:
      duration_hours: 8
      blocking: true

  - id: 18
    name: "Secagem em prateleiras"
    type: "dry"

  - id: 19
    name: "Transferir para Câmara 2 (início da maturação)"
    type: "transfer"
    operator_input_required:
      - chamber_2_entry_date
    stored_values:
      - chamber_2_entry_date
    expected_intent: "RegisterChamberEntryDateIntent"
    input_prompt: "Registre a data de entrada na câmara 2 dizendo: 'entrada na câmara dois hoje' ou 'entrada na câmara dois dia quinze de janeiro'."
    instructions:
      - "Colocar plaquinha com data de produção na tábua"

  - id: 20
    name: "Maturação em Câmara 2"
    type: "maintenance"
    reminder:
      frequency: "daily"
    maturation_control:
      duration_days: 90
      count_from: "chamber_2_entry_date"
    instructions:
      - "Virar os queijos diariamente"
      - "Trocar tábua se estiver molhada"

  - id: 21
    name: "Conclusão"
    type: "completion"
    instructions:
      - "Lote finalizado com sucesso"
      - "Queijos prontos para comercialização"